### ISSUE TITLE
Scheme already exists: Cookies

### ISSUE THREAD

**Issue by lumimario** [Gibe/Umbraco.Community.AzureSSO#35]
Hi there,

I have upgraded a site from Umbraco v10 to v13 and now I'm getting an error message like:

```
System.InvalidOperationException: Scheme already exists: Cookies
   at Microsoft.AspNetCore.Authentication.AuthenticationOptions.AddScheme(String name, Action`1 configureBuilder)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Authentication.AuthenticationSchemeProvider..ctor(IOptions`1 options, IDictionary`2 schemes)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSite

.....
```

If I remove the SSO package the site runs fine, so I guess there's some collision somewhere.... Any ideas?

**Comment by stevetemple** [comment]
> Hi there,
> 
> 
> 
> I have upgraded a site from Umbraco v10 to v13 and now I'm getting an error message like:
> 
> 
> 
> ```
> 
> System.InvalidOperationException: Scheme already exists: Cookies
> 
>    at Microsoft.AspNetCore.Authentication.AuthenticationOptions.AddScheme(String name, Action`1 configureBuilder)
> 
>    at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
> 
>    at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
> 
>    at Microsoft.AspNetCore.Authentication.AuthenticationSchemeProvider..ctor(IOptions`1 options, IDictionary`2 schemes)
> 
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
> 
>    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
> 
>    at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
> 
>    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
> 
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
> 
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
> 
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
> 
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSite
> 
> 
> 
> .....
> 
> ```
> 
> 
> 
> If I remove the SSO package the site runs fine, so I guess there's some collision somewhere.... Any ideas?

Looks like you might be using another sso provider as well?

**Comment by lumimario** [comment]
That's the weird thing, I don't. Or I can't find the code that adds that. Is there anything saved on the database? Maybe there's a duplication in a table?

This is an upgrade to 13, and we are currently using the same code for V10.

**Comment by lumimario** [comment]
this was an user error. It's all good now.
